modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="herobrines_fortress"
version="1.0.0"
displayName="Herobrines fortress"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Shadowmaster9112 - Mason, MCreator"

[[dependencies.herobrines_fortress]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



